In [1]:
import pandas as pd
import os
import sys

# Add project root to PYTHONPATH
project_root = os.path.abspath("../")
sys.path.append(project_root)

from src.preprocessing.load_data import load_dataset
from src.preprocessing.clean_data import clean_data
from src.preprocessing.feature_engineering import add_features

In [2]:
RAW_DATA_PATH = "../data/raw/Final_data_set.csv"

df_raw = load_dataset(RAW_DATA_PATH)

print("[INFO] Raw dataset loaded. Shape:", df_raw.shape)
df_raw.head()

[INFO] Loading dataset from: ../data/raw/Final_data_set.csv
[INFO] Final standardized columns: ['timestamp', 'load_actual', 'temperature', 'humidity', 'dew_point', 'solar_generation', 'wind_generation']
[INFO] Rows loaded: 43825
[INFO] Raw dataset loaded. Shape: (43825, 7)

,timestamp,load_actual,temperature,humidity,dew_point,solar_generation,wind_generation
0,2014-12-31T23:00,NaN,7.5,81,4.5,NaN,NaN
1,2015-01-01T00:00,NaN,7.3,81,4.2,NaN,NaN
2,2015-01-01T01:00,22734.0,7.0,81,3.9,50.0,5461.0
3,2015-01-01T02:00,21286.0,6.8,81,3.7,50.0,5238.0
4,2015-01-01T03:00,20264.0,6.9,79,3.5,42.0,4935.0

In [3]:
df_clean = clean_data(df_raw)

print("[INFO] Dataset after cleaning. Shape:", df_clean.shape)
df_clean.head()

[INFO] Cleaning dataset...
[INFO] Data cleaning complete. Rows: 43825
[INFO] Dataset after cleaning. Shape: (43825, 7)

,timestamp,load_actual,temperature,humidity,dew_point,solar_generation,wind_generation
0,2014-12-31 23:00:00,22734.0,7.5,81,4.5,50.0,5461.0
1,2015-01-01 00:00:00,22734.0,7.3,81,4.2,50.0,5461.0
2,2015-01-01 01:00:00,22734.0,7.0,81,3.9,50.0,5461.0
3,2015-01-01 02:00:00,21286.0,6.8,81,3.7,50.0,5238.0
4,2015-01-01 03:00:00,20264.0,6.9,79,3.5,42.0,4935.0

In [4]:
df_features = add_features(df_clean)

print("[INFO] Dataset after feature engineering. Shape:", df_features.shape)
df_features.head()

[INFO] Adding calendar, lag, and rolling features...
[INFO] Feature engineering complete.
[INFO] Dataset after feature engineering. Shape: (43657, 19)

,timestamp,load_actual,temperature,humidity,dew_point,solar_generation,wind_generation,hour,day_of_week,month,is_weekend,hour_sin,hour_cos,load_lag_1,load_lag_24,load_lag_168,rolling_mean_24,rolling_std_24,rolling_mean_168
0,2015-01-07 23:00:00,28222.0,2.2,32,-12.6,52.0,1015.0,23,2,1,0,-0.258819,0.965926,31404.0,25555.0,22734.0,31718.583333,5933.401136,27376.958333
1,2015-01-08 00:00:00,25790.0,0.8,28,-15.6,43.0,1235.0,0,3,1,0,0.000000,1.000000,28222.0,23341.0,22734.0,31820.625000,5802.679387,27395.148810
2,2015-01-08 01:00:00,24481.0,-0.6,25,-18.0,36.0,1443.0,1,3,1,0,0.258819,0.965926,25790.0,22029.0,22734.0,31922.791667,5642.149945,27405.547619
3,2015-01-08 02:00:00,23883.0,-2.5,27,-19.2,36.0,1579.0,2,3,1,0,0.500000,0.866025,24481.0,21456.0,21286.0,32023.916667,5465.376314,27421.005952
4,2015-01-08 03:00:00,23761.0,-3.5,29,-19.2,36.0,1692.0,3,3,1,0,0.707107,0.707107,23883.0,21457.0,20264.0,32119.916667,5289.089097,27441.821429

In [5]:
PROCESSED_PATH = "../data/processed/featured_dataset.csv"

df_features.to_csv(PROCESSED_PATH, index=False)

print("[INFO] Processed dataset saved at:", PROCESSED_PATH)
print("[INFO] File size:", os.path.getsize(PROCESSED_PATH), "bytes")

[INFO] Processed dataset saved at: ../data/processed/featured_dataset.csv
[INFO] File size: 7711329 bytes